steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  id: Deploy to GKE onprem
  args:
  - '-c'
  - |
    set -x && \
    export KUBECONFIG="$(pwd)/gateway-kubeconfig" && \
    gcloud alpha container hub memberships get-credentials my-user-cluster1 && \
    kubectl --kubeconfig gateway-kubeconfig apply -f myapp.yaml