apiVersion: v1
kind: Namespace
metadata:
  name: hello

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  namespace: hello
spec:
  selector:
    matchLabels:
      app: helloweb
  replicas: 3
  template:
    metadata:
      labels:
        app: helloweb
    spec:
      containers:
      - name: helloweb
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080