apiVersion: v1
kind: Namespace
metadata:
  name: hello

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  namespace: hello
spec:
  selector:
    matchLabels:
      app: helloweb
  replicas: 2
  template:
    metadata:
      labels:
        app: helloweb
    spec:
      containers:
      - name: helloweb
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: helloweb-service
  namespace: hello
spec:
  type: LoadBalancer
  selector:
    app: helloweb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080